const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "923184474176";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "available" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "true"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "It'x Suhail",

  sessionName:process.env.SESSION_ID || "SUHAIL_20_48_08_26_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTY4LFxuICAgICAgICAyNDIsXG4gICAgICAgIDM3LFxuICAgICAgICAxNjEsXG4gICAgICAgIDMzLFxuICAgICAgICAxOTEsXG4gICAgICAgIDI3LFxuICAgICAgICAxNjUsXG4gICAgICAgIDE4NSxcbiAgICAgICAgMTAyLFxuICAgICAgICA4MixcbiAgICAgICAgNzIsXG4gICAgICAgIDE3MixcbiAgICAgICAgMjE5LFxuICAgICAgICA3NixcbiAgICAgICAgMTI3LFxuICAgICAgICAxNDMsXG4gICAgICAgIDIyMyxcbiAgICAgICAgMjksXG4gICAgICAgIDIxMixcbiAgICAgICAgMjMzLFxuICAgICAgICAxNjMsXG4gICAgICAgIDEyMyxcbiAgICAgICAgMTAyLFxuICAgICAgICA0NyxcbiAgICAgICAgMjM4LFxuICAgICAgICA2MCxcbiAgICAgICAgMTEzLFxuICAgICAgICA3MSxcbiAgICAgICAgMTU2LFxuICAgICAgICA5NixcbiAgICAgICAgMTE0XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDEwLFxuICAgICAgICAxNjUsXG4gICAgICAgIDIzNyxcbiAgICAgICAgMjQwLFxuICAgICAgICAyNDUsXG4gICAgICAgIDExNyxcbiAgICAgICAgMzksXG4gICAgICAgIDE3MSxcbiAgICAgICAgMjM4LFxuICAgICAgICAxMzYsXG4gICAgICAgIDE3MCxcbiAgICAgICAgMTA3LFxuICAgICAgICAxODcsXG4gICAgICAgIDIzMixcbiAgICAgICAgMjMwLFxuICAgICAgICAxNjcsXG4gICAgICAgIDE3MCxcbiAgICAgICAgMTYzLFxuICAgICAgICA1OCxcbiAgICAgICAgMTYxLFxuICAgICAgICAyMTIsXG4gICAgICAgIDI0OCxcbiAgICAgICAgMTE2LFxuICAgICAgICAxMDksXG4gICAgICAgIDE0OCxcbiAgICAgICAgMTMyLFxuICAgICAgICAxODcsXG4gICAgICAgIDE3NyxcbiAgICAgICAgMTk1LFxuICAgICAgICAyMDEsXG4gICAgICAgIDEzMCxcbiAgICAgICAgNTFcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwicGFpcmluZ0VwaGVtZXJhbEtleVBhaXJcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDEyMCxcbiAgICAgICAgMjA0LFxuICAgICAgICAyMyxcbiAgICAgICAgMjQxLFxuICAgICAgICAyMTQsXG4gICAgICAgIDI0OSxcbiAgICAgICAgMjAwLFxuICAgICAgICAxMTUsXG4gICAgICAgIDEyLFxuICAgICAgICA4NyxcbiAgICAgICAgMjA2LFxuICAgICAgICAxMjIsXG4gICAgICAgIDIwMCxcbiAgICAgICAgMzMsXG4gICAgICAgIDQ4LFxuICAgICAgICAzNixcbiAgICAgICAgODQsXG4gICAgICAgIDE4NixcbiAgICAgICAgMjI2LFxuICAgICAgICAyNTUsXG4gICAgICAgIDQzLFxuICAgICAgICAyMSxcbiAgICAgICAgMzYsXG4gICAgICAgIDE5NyxcbiAgICAgICAgMjUzLFxuICAgICAgICAxNjIsXG4gICAgICAgIDE2MCxcbiAgICAgICAgMjIwLFxuICAgICAgICA4NyxcbiAgICAgICAgOTcsXG4gICAgICAgIDIzNixcbiAgICAgICAgNzZcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTAsXG4gICAgICAgIDExNCxcbiAgICAgICAgMTg1LFxuICAgICAgICAyNDMsXG4gICAgICAgIDExOSxcbiAgICAgICAgMjcsXG4gICAgICAgIDI0LFxuICAgICAgICA4OSxcbiAgICAgICAgMTgsXG4gICAgICAgIDE4OSxcbiAgICAgICAgMSxcbiAgICAgICAgNTksXG4gICAgICAgIDE2MCxcbiAgICAgICAgMTc5LFxuICAgICAgICAyMTEsXG4gICAgICAgIDI0LFxuICAgICAgICA1MSxcbiAgICAgICAgMTM1LFxuICAgICAgICAyMTAsXG4gICAgICAgIDIsXG4gICAgICAgIDEzOSxcbiAgICAgICAgMjgsXG4gICAgICAgIDIyMixcbiAgICAgICAgMTg0LFxuICAgICAgICAxMzksXG4gICAgICAgIDg3LFxuICAgICAgICA2OCxcbiAgICAgICAgMjM4LFxuICAgICAgICAyMzEsXG4gICAgICAgIDE5LFxuICAgICAgICAzNyxcbiAgICAgICAgMTE4XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZElkZW50aXR5S2V5XCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA4LFxuICAgICAgICA5NixcbiAgICAgICAgMTI3LFxuICAgICAgICA2MCxcbiAgICAgICAgMzEsXG4gICAgICAgIDIsXG4gICAgICAgIDEzMyxcbiAgICAgICAgMSxcbiAgICAgICAgMTY5LFxuICAgICAgICAzOSxcbiAgICAgICAgMTIyLFxuICAgICAgICA4MSxcbiAgICAgICAgNyxcbiAgICAgICAgMjQwLFxuICAgICAgICAxNyxcbiAgICAgICAgMTk1LFxuICAgICAgICAyNTAsXG4gICAgICAgIDIwMixcbiAgICAgICAgMzcsXG4gICAgICAgIDYxLFxuICAgICAgICAxNTIsXG4gICAgICAgIDIyNSxcbiAgICAgICAgMjQyLFxuICAgICAgICAyNDYsXG4gICAgICAgIDE1NixcbiAgICAgICAgMjUsXG4gICAgICAgIDE1OCxcbiAgICAgICAgMTEwLFxuICAgICAgICA2MixcbiAgICAgICAgMTg3LFxuICAgICAgICAxMTksXG4gICAgICAgIDExMFxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxOTQsXG4gICAgICAgIDI0MixcbiAgICAgICAgMTE2LFxuICAgICAgICA1NSxcbiAgICAgICAgMTg1LFxuICAgICAgICAxMTgsXG4gICAgICAgIDIwOSxcbiAgICAgICAgNjcsXG4gICAgICAgIDU1LFxuICAgICAgICAxNjgsXG4gICAgICAgIDIxMixcbiAgICAgICAgMjI2LFxuICAgICAgICAyNCxcbiAgICAgICAgMjAyLFxuICAgICAgICAxNSxcbiAgICAgICAgMjI3LFxuICAgICAgICAyMjksXG4gICAgICAgIDI1MCxcbiAgICAgICAgMTAyLFxuICAgICAgICAyMjUsXG4gICAgICAgIDMsXG4gICAgICAgIDYwLFxuICAgICAgICAxNDYsXG4gICAgICAgIDE1MCxcbiAgICAgICAgMjIwLFxuICAgICAgICAyMzksXG4gICAgICAgIDE5MixcbiAgICAgICAgMjA3LFxuICAgICAgICAxNzIsXG4gICAgICAgIDk5LFxuICAgICAgICAyMTQsXG4gICAgICAgIDEwMFxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRQcmVLZXlcIjoge1xuICAgIFwia2V5UGFpclwiOiB7XG4gICAgICBcInByaXZhdGVcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAxODQsXG4gICAgICAgICAgMjEsXG4gICAgICAgICAgMTc1LFxuICAgICAgICAgIDI0NyxcbiAgICAgICAgICAxNTQsXG4gICAgICAgICAgMjQ5LFxuICAgICAgICAgIDI0MCxcbiAgICAgICAgICAxMjcsXG4gICAgICAgICAgMjUxLFxuICAgICAgICAgIDg0LFxuICAgICAgICAgIDIxNCxcbiAgICAgICAgICA2MSxcbiAgICAgICAgICA1OCxcbiAgICAgICAgICAyNDgsXG4gICAgICAgICAgMzAsXG4gICAgICAgICAgMjIsXG4gICAgICAgICAgMTI0LFxuICAgICAgICAgIDEwMixcbiAgICAgICAgICAxNDgsXG4gICAgICAgICAgMjM1LFxuICAgICAgICAgIDc3LFxuICAgICAgICAgIDIwMyxcbiAgICAgICAgICAyMTcsXG4gICAgICAgICAgNDAsXG4gICAgICAgICAgNDksXG4gICAgICAgICAgMTM5LFxuICAgICAgICAgIDEwLFxuICAgICAgICAgIDY2LFxuICAgICAgICAgIDUxLFxuICAgICAgICAgIDE1MixcbiAgICAgICAgICAxNDIsXG4gICAgICAgICAgMTIxXG4gICAgICAgIF1cbiAgICAgIH0sXG4gICAgICBcInB1YmxpY1wiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDgzLFxuICAgICAgICAgIDE1MCxcbiAgICAgICAgICA1LFxuICAgICAgICAgIDI0OCxcbiAgICAgICAgICAxNzEsXG4gICAgICAgICAgMTUsXG4gICAgICAgICAgODAsXG4gICAgICAgICAgMjIsXG4gICAgICAgICAgMjMsXG4gICAgICAgICAgNjAsXG4gICAgICAgICAgMTM1LFxuICAgICAgICAgIDEwMCxcbiAgICAgICAgICAxMjksXG4gICAgICAgICAgMjAzLFxuICAgICAgICAgIDIxNCxcbiAgICAgICAgICA4MCxcbiAgICAgICAgICAxNjMsXG4gICAgICAgICAgMCxcbiAgICAgICAgICAxMzQsXG4gICAgICAgICAgODYsXG4gICAgICAgICAgMTk3LFxuICAgICAgICAgIDEyNyxcbiAgICAgICAgICAxNjMsXG4gICAgICAgICAgMTY3LFxuICAgICAgICAgIDI0NixcbiAgICAgICAgICAyMzQsXG4gICAgICAgICAgMjI5LFxuICAgICAgICAgIDI1NCxcbiAgICAgICAgICAzOCxcbiAgICAgICAgICA3MixcbiAgICAgICAgICAxODYsXG4gICAgICAgICAgOTVcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH0sXG4gICAgXCJzaWduYXR1cmVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxNDgsXG4gICAgICAgIDY3LFxuICAgICAgICA3OCxcbiAgICAgICAgNTAsXG4gICAgICAgIDE4OSxcbiAgICAgICAgMTcwLFxuICAgICAgICAyMDUsXG4gICAgICAgIDU4LFxuICAgICAgICAxMyxcbiAgICAgICAgMjQ2LFxuICAgICAgICA4NyxcbiAgICAgICAgMjksXG4gICAgICAgIDEwMSxcbiAgICAgICAgMzcsXG4gICAgICAgIDk5LFxuICAgICAgICAxMDksXG4gICAgICAgIDIsXG4gICAgICAgIDk1LFxuICAgICAgICAzOSxcbiAgICAgICAgMjQ5LFxuICAgICAgICAxODgsXG4gICAgICAgIDIzMyxcbiAgICAgICAgMTQ3LFxuICAgICAgICA0MyxcbiAgICAgICAgNjUsXG4gICAgICAgIDEzOSxcbiAgICAgICAgMTQ3LFxuICAgICAgICAyMDEsXG4gICAgICAgIDEwNSxcbiAgICAgICAgODksXG4gICAgICAgIDIzLFxuICAgICAgICA5MCxcbiAgICAgICAgODgsXG4gICAgICAgIDE5MyxcbiAgICAgICAgNzEsXG4gICAgICAgIDI1MSxcbiAgICAgICAgMjAxLFxuICAgICAgICAyMjMsXG4gICAgICAgIDcwLFxuICAgICAgICAxMjgsXG4gICAgICAgIDIzMixcbiAgICAgICAgMTk5LFxuICAgICAgICAyMTIsXG4gICAgICAgIDE3NCxcbiAgICAgICAgMjksXG4gICAgICAgIDI1NCxcbiAgICAgICAgMTA1LFxuICAgICAgICAyMTEsXG4gICAgICAgIDE4MixcbiAgICAgICAgNDIsXG4gICAgICAgIDcyLFxuICAgICAgICAxNjMsXG4gICAgICAgIDEzNCxcbiAgICAgICAgNTgsXG4gICAgICAgIDEwNixcbiAgICAgICAgNTUsXG4gICAgICAgIDMyLFxuICAgICAgICA2OSxcbiAgICAgICAgMjI3LFxuICAgICAgICAyNyxcbiAgICAgICAgMjAxLFxuICAgICAgICAxNzAsXG4gICAgICAgIDc4LFxuICAgICAgICA4XG4gICAgICBdXG4gICAgfSxcbiAgICBcImtleUlkXCI6IDFcbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25JZFwiOiA4MixcbiAgXCJhZHZTZWNyZXRLZXlcIjogXCJYMHNuai93dENoWTY5bjJwODdoeHAxUEhocDRYNWFJQXVSdHk0RFltcmFJPVwiLFxuICBcInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlc1wiOiBbXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjIzNDgwNzA1NDk0NDNAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIkREQjdFRERFQTg0RjA0NjU2OUUzRjQ0NTgwODdDMTM4XCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcyNDcwNTMxN1xuICAgIH1cbiAgXSxcbiAgXCJuZXh0UHJlS2V5SWRcIjogMzEsXG4gIFwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWRcIjogMzEsXG4gIFwiYWNjb3VudFN5bmNDb3VudGVyXCI6IDAsXG4gIFwiYWNjb3VudFNldHRpbmdzXCI6IHtcbiAgICBcInVuYXJjaGl2ZUNoYXRzXCI6IGZhbHNlXG4gIH0sXG4gIFwiZGV2aWNlSWRcIjogXCJ5dzYtejBYUlNsR1QzTnlkelg3N1RBXCIsXG4gIFwicGhvbmVJZFwiOiBcImYwZGIxNDg0LTQyNDgtNDhjMS1hN2Y1LWQyYzE4ODNhNTEyZFwiLFxuICBcImlkZW50aXR5SWRcIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAyMDYsXG4gICAgICAxMjEsXG4gICAgICAxMTAsXG4gICAgICAxOTEsXG4gICAgICAxOTQsXG4gICAgICAxOTIsXG4gICAgICAyMDAsXG4gICAgICAxMDksXG4gICAgICAyMDQsXG4gICAgICA4NyxcbiAgICAgIDExOSxcbiAgICAgIDExNixcbiAgICAgIDk3LFxuICAgICAgMTc4LFxuICAgICAgMTY1LFxuICAgICAgMTc4LFxuICAgICAgMjQ4LFxuICAgICAgMjU1LFxuICAgICAgMjA5LFxuICAgICAgMTMwXG4gICAgXVxuICB9LFxuICBcInJlZ2lzdGVyZWRcIjogdHJ1ZSxcbiAgXCJiYWNrdXBUb2tlblwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDQwLFxuICAgICAgMjEwLFxuICAgICAgMTAyLFxuICAgICAgNzYsXG4gICAgICAxNDgsXG4gICAgICAyMTcsXG4gICAgICAyMDMsXG4gICAgICAxMTQsXG4gICAgICAxMjEsXG4gICAgICAxNDEsXG4gICAgICAxNjIsXG4gICAgICAxNzgsXG4gICAgICA4LFxuICAgICAgOTYsXG4gICAgICA3NixcbiAgICAgIDE0MSxcbiAgICAgIDIzOSxcbiAgICAgIDE2NSxcbiAgICAgIDE0NCxcbiAgICAgIDg4XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdHJhdGlvblwiOiB7fSxcbiAgXCJwYWlyaW5nQ29kZVwiOiBcIlA2QlFDVkROXCIsXG4gIFwibWVcIjoge1xuICAgIFwiaWRcIjogXCIyMzQ4MDcwNTQ5NDQzOjQwQHMud2hhdHNhcHAubmV0XCIsXG4gICAgXCJsaWRcIjogXCIyNDczOTIyOTc0OTQxMzo0MEBsaWRcIlxuICB9LFxuICBcImFjY291bnRcIjoge1xuICAgIFwiZGV0YWlsc1wiOiBcIkNNdWc4S1FFRUpyVXM3WUdHQXNnQUNnQVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZUtleVwiOiBcIjhNWUsrQlE2RDRUYVdMQ3JXSk5pNlR3eDNPSEo2QTVxakhXVWUwTzNHbWs9XCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlXCI6IFwiRXBYWFVSRkwzS2xHWEhJaEpnMHQ0M2NZMnpmUEJyZXBSN0VuTHFtZ3RBRmtCMHYyNjRqUC8vSm9udElGUEQrVG1uVDFGeHkzZlZ5Q3Z4ZHErdng2RGc9PVwiLFxuICAgIFwiZGV2aWNlU2lnbmF0dXJlXCI6IFwidGp4RFVRbzJ6VGJqUWtBUW1vd2pnbVpoNFlBZlowMkVMZGg1RjdRS08rNDVsZmRjNGRoOWR3UzdFemRoWVg3cEpJSEZ2NmtBWGpSZ21IL2hmMWRaQUE9PVwiXG4gIH0sXG4gIFwic2lnbmFsSWRlbnRpdGllc1wiOiBbXG4gICAge1xuICAgICAgXCJpZGVudGlmaWVyXCI6IHtcbiAgICAgICAgXCJuYW1lXCI6IFwiMjM0ODA3MDU0OTQ0Mzo0MEBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImRldmljZUlkXCI6IDBcbiAgICAgIH0sXG4gICAgICBcImlkZW50aWZpZXJLZXlcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA1LFxuICAgICAgICAgIDI0MCxcbiAgICAgICAgICAxOTgsXG4gICAgICAgICAgMTAsXG4gICAgICAgICAgMjQ4LFxuICAgICAgICAgIDIwLFxuICAgICAgICAgIDU4LFxuICAgICAgICAgIDE1LFxuICAgICAgICAgIDEzMixcbiAgICAgICAgICAyMTgsXG4gICAgICAgICAgODgsXG4gICAgICAgICAgMTc2LFxuICAgICAgICAgIDE3MSxcbiAgICAgICAgICA4OCxcbiAgICAgICAgICAxNDcsXG4gICAgICAgICAgOTgsXG4gICAgICAgICAgMjMzLFxuICAgICAgICAgIDYwLFxuICAgICAgICAgIDQ5LFxuICAgICAgICAgIDIyMCxcbiAgICAgICAgICAyMjUsXG4gICAgICAgICAgMjAxLFxuICAgICAgICAgIDIzMixcbiAgICAgICAgICAxNCxcbiAgICAgICAgICAxMDYsXG4gICAgICAgICAgMTQwLFxuICAgICAgICAgIDExNyxcbiAgICAgICAgICAxNDgsXG4gICAgICAgICAgMTIzLFxuICAgICAgICAgIDY3LFxuICAgICAgICAgIDE4MyxcbiAgICAgICAgICAyNixcbiAgICAgICAgICAxMDVcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH1cbiAgXSxcbiAgXCJwbGF0Zm9ybVwiOiBcImFuZHJvaWRcIixcbiAgXCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXBcIjogMTcyNDcwNTMxMCxcbiAgXCJteUFwcFN0YXRlS2V5SWRcIjogXCJBQUFBQURiT1wiXG59IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBRGJPLmpzb24iOiAie1wia2V5RGF0YVwiOlwiN2w5blNFSEUvZG01SkpscFUwTnFwREJhazRXclpuZUIxdU5rYWZQa0J4VT1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxMTUxMDc4NDc1LFwiY3VycmVudEluZGV4XCI6MTAsXCJkZXZpY2VJbmRleGVzXCI6WzAsOSwxMF19LFwidGltZXN0YW1wXCI6XCIwXCJ9Igp9",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
